import { createContext, useContext, useState, useCallback, type ReactNode } from 'react';

export type Locale = 'fr' | 'en';

const translations = {
  fr: {
    // Header
    'nav.howItWorks': 'Comment ça marche',
    'nav.about': 'À propos',
    // Hero
    'hero.subtitle': 'Smart Knowledge for Analytics & Launch',
    'hero.tagline': 'Votre copilote IA pour SEO, indexation et visibilité web.',
    // Search
    'search.placeholder': 'Entrez l\'URL de votre site (ex: example.com)',
    'search.button': 'Analyser',
    'search.loading': 'Analyse...',
    'search.urlRequired': 'URL requise',
    'search.urlRequiredDesc': 'Veuillez entrer l\'URL du site à analyser.',
    'search.complete': 'Analyse terminée',
    'search.scoreResult': 'Score SEO : {score}/100 — {fixes} fichier(s) généré(s)',
    'search.error': 'Erreur d\'analyse',
    'search.errorDesc': 'Impossible d\'analyser ce site.',
    'search.genericError': 'Erreur',
    'search.genericErrorDesc': 'Une erreur est survenue lors de l\'analyse.',
    // Empty state
    'empty.title': 'Entrez l\'URL d\'un site pour lancer l\'analyse SEO',
    'empty.subtitle': 'SKAL IA analysera, générera les corrections et produira un rapport complet.',
    // Results
    'results.analyzedUrl': 'Analyse de',
    'results.issues': 'Problèmes détectés',
    'results.noIssues': '🎉 Excellent ! Aucun problème SEO majeur détecté.',
    'results.highPriority': 'Haute priorité',
    'results.mediumPriority': 'Priorité moyenne',
    'results.lowPriority': 'Basse priorité',
    // Score
    'score.title': 'Score de visibilité SEO',
    'score.excellent': 'Excellent',
    'score.good': 'Bon',
    'score.needsWork': 'À améliorer',
    'score.critical': 'Critique',
    // Score breakdown
    'score.breakdown': 'Détail du score',
    // Confidence
    'confidence.title': 'Niveau de confiance',
    'confidence.verified': 'Vérifié',
    'confidence.partial': 'Partiel',
    'confidence.uncertain': 'Incertain',
    'confidence.notChecked': 'Non vérifié',
    // Checklist
    'checklist.title': 'Checklist SEO',
    'checklist.validated': 'validés',
    'checklist.titlePresent': 'Balise title présente',
    'checklist.descPresent': 'Meta description présente',
    'checklist.h1Unique': 'Balise H1 unique',
    'checklist.langDefined': 'Attribut lang défini',
    'checklist.canonical': 'URL canonique définie',
    'checklist.robotsTxt': 'Fichier robots.txt présent',
    'checklist.sitemap': 'Sitemap XML trouvé',
    'checklist.sitemapValid': 'Structure sitemap valide',
    'checklist.ogTags': 'Balises Open Graph',
    'checklist.twitterCards': 'Twitter Cards',
    'checklist.viewport': 'Meta viewport (mobile)',
    'checklist.indexable': 'Page indexable',
    'checklist.nobrokenLinks': 'Aucun lien cassé',
    // Action report
    'report.title': 'Rapport d\'actions',
    'report.automated': 'Actions automatiques',
    'report.manual': 'Actions manuelles requises',
    'report.priorityHigh': 'Haute',
    'report.priorityMedium': 'Moyenne',
    'report.priorityLow': 'Basse',
    // Generated fixes
    'fixes.title': 'Fichiers générés automatiquement',
    'fixes.preview': 'Aperçu',
    'fixes.hide': 'Masquer',
    'fixes.autoGenerated': '✅ Auto-généré',
    'fixes.needsReview': '📝 À vérifier',
    // Issues
    'issue.whyProblem': '❌ Pourquoi c\'est un problème',
    'issue.howToFix': '✅ Comment corriger',
    'issue.highPriority': 'Haute priorité',
    'issue.mediumPriority': 'Priorité moyenne',
    'issue.lowPriority': 'Basse priorité',
    'issue.manual': 'Correction manuelle',
    'issue.automated': 'Automatisable',
    'issue.semiAutomated': 'Semi-automatisé',
    // Detail sections
    'detail.brokenLinks': 'Liens cassés',
    'detail.gscInstructions': 'Instructions Google Search Console',
    'detail.sitemapInfo': 'Informations Sitemap',
    'detail.sitemapUrl': 'URL du sitemap',
    'detail.sitemapUrls': 'URLs dans le sitemap',
    'detail.sitemapValid': 'Structure valide',
    'detail.yes': 'Oui',
    'detail.no': 'Non',
    'detail.contentAnalysis': 'Analyse du contenu',
    'detail.wordCount': 'Nombre de mots',
    'detail.readability': 'Score de lisibilité',
    'detail.topKeywords': 'Mots-clés principaux',
    'detail.duplicateContent': '⚠️ Contenu dupliqué détecté',
    'detail.duplicateSections': 'section(s) répétée(s)',
    'detail.aiSuggestions': 'Suggestions IA',
    'detail.suggestedTitle': '💡 Titre suggéré',
    'detail.suggestedDesc': '💡 Meta description suggérée',
    'detail.improvements': '🚀 Améliorations recommandées',
    'detail.multilingual': 'Analyse multilingue',
    'detail.langVersions': 'Versions linguistiques détectées',
    'detail.merchant': 'Analyse Google Merchant Center',
    'detail.structuredDataFound': '✅ Données structurées Product (JSON-LD) détectées',
    'detail.noStructuredData': '⚠️ Aucune donnée structurée Product détectée',
    'detail.merchantGuide': 'Guide Google Merchant Center',
    'detail.inStock': 'En stock',
    'detail.outOfStock': 'Rupture',
    'detail.availability': 'Disponibilité',
    'detail.noName': 'Produit sans nom',
    // Footer
    'footer.tagline': 'SKAL IA — Votre copilote IA pour SEO, indexation et visibilité web.',
    // Errors
    'error.inaccessible': 'Inaccessible',
    'error.code': 'Erreur',
  },
  en: {
    'nav.howItWorks': 'How it works',
    'nav.about': 'About',
    'hero.subtitle': 'Smart Knowledge for Analytics & Launch',
    'hero.tagline': 'Your AI copilot for SEO, indexing and web visibility.',
    'search.placeholder': 'Enter your website URL (e.g. example.com)',
    'search.button': 'Analyze',
    'search.loading': 'Analyzing...',
    'search.urlRequired': 'URL required',
    'search.urlRequiredDesc': 'Please enter the URL of the site to analyze.',
    'search.complete': 'Analysis complete',
    'search.scoreResult': 'SEO Score: {score}/100 — {fixes} file(s) generated',
    'search.error': 'Analysis error',
    'search.errorDesc': 'Unable to analyze this site.',
    'search.genericError': 'Error',
    'search.genericErrorDesc': 'An error occurred during analysis.',
    'empty.title': 'Enter a website URL to start the SEO analysis',
    'empty.subtitle': 'SKAL IA will analyze, generate fixes and produce a comprehensive report.',
    'results.analyzedUrl': 'Analysis of',
    'results.issues': 'Issues detected',
    'results.noIssues': '🎉 Excellent! No major SEO issues detected.',
    'results.highPriority': 'High priority',
    'results.mediumPriority': 'Medium priority',
    'results.lowPriority': 'Low priority',
    'score.title': 'SEO Visibility Score',
    'score.excellent': 'Excellent',
    'score.good': 'Good',
    'score.needsWork': 'Needs improvement',
    'score.critical': 'Critical',
    'score.breakdown': 'Score breakdown',
    'confidence.title': 'Confidence level',
    'confidence.verified': 'Verified',
    'confidence.partial': 'Partial',
    'confidence.uncertain': 'Uncertain',
    'confidence.notChecked': 'Not checked',
    'checklist.title': 'SEO Checklist',
    'checklist.validated': 'validated',
    'checklist.titlePresent': 'Title tag present',
    'checklist.descPresent': 'Meta description present',
    'checklist.h1Unique': 'Unique H1 tag',
    'checklist.langDefined': 'Language attribute defined',
    'checklist.canonical': 'Canonical URL defined',
    'checklist.robotsTxt': 'robots.txt file present',
    'checklist.sitemap': 'XML Sitemap found',
    'checklist.sitemapValid': 'Valid sitemap structure',
    'checklist.ogTags': 'Open Graph tags',
    'checklist.twitterCards': 'Twitter Cards',
    'checklist.viewport': 'Viewport meta (mobile)',
    'checklist.indexable': 'Page indexable',
    'checklist.nobrokenLinks': 'No broken links',
    'report.title': 'Action Report',
    'report.automated': 'Automated actions',
    'report.manual': 'Manual actions required',
    'report.priorityHigh': 'High',
    'report.priorityMedium': 'Medium',
    'report.priorityLow': 'Low',
    'fixes.title': 'Auto-generated files',
    'fixes.preview': 'Preview',
    'fixes.hide': 'Hide',
    'fixes.autoGenerated': '✅ Auto-generated',
    'fixes.needsReview': '📝 Needs review',
    'issue.whyProblem': '❌ Why this is a problem',
    'issue.howToFix': '✅ How to fix',
    'issue.highPriority': 'High priority',
    'issue.mediumPriority': 'Medium priority',
    'issue.lowPriority': 'Low priority',
    'issue.manual': 'Manual fix',
    'issue.automated': 'Automatable',
    'issue.semiAutomated': 'Semi-automated',
    'detail.brokenLinks': 'Broken links',
    'detail.gscInstructions': 'Google Search Console Instructions',
    'detail.sitemapInfo': 'Sitemap Information',
    'detail.sitemapUrl': 'Sitemap URL',
    'detail.sitemapUrls': 'URLs in sitemap',
    'detail.sitemapValid': 'Valid structure',
    'detail.yes': 'Yes',
    'detail.no': 'No',
    'detail.contentAnalysis': 'Content Analysis',
    'detail.wordCount': 'Word count',
    'detail.readability': 'Readability score',
    'detail.topKeywords': 'Top keywords',
    'detail.duplicateContent': '⚠️ Duplicate content detected',
    'detail.duplicateSections': 'repeated section(s)',
    'detail.aiSuggestions': 'AI Suggestions',
    'detail.suggestedTitle': '💡 Suggested title',
    'detail.suggestedDesc': '💡 Suggested meta description',
    'detail.improvements': '🚀 Recommended improvements',
    'detail.multilingual': 'Multilingual Analysis',
    'detail.langVersions': 'Detected language versions',
    'detail.merchant': 'Google Merchant Center Analysis',
    'detail.structuredDataFound': '✅ Product structured data (JSON-LD) detected',
    'detail.noStructuredData': '⚠️ No Product structured data detected',
    'detail.merchantGuide': 'Google Merchant Center Guide',
    'detail.inStock': 'In stock',
    'detail.outOfStock': 'Out of stock',
    'detail.availability': 'Availability',
    'detail.noName': 'Unnamed product',
    'footer.tagline': 'SKAL IA — Your AI copilot for SEO, indexing and web visibility.',
    'error.inaccessible': 'Inaccessible',
    'error.code': 'Error',
  },
} as const;

type TranslationKey = keyof typeof translations.fr;

interface I18nContextType {
  locale: Locale;
  setLocale: (locale: Locale) => void;
  t: (key: TranslationKey, params?: Record<string, string | number>) => string;
}

const I18nContext = createContext<I18nContextType | null>(null);

export function I18nProvider({ children }: { children: ReactNode }) {
  const [locale, setLocale] = useState<Locale>('fr');

  const t = useCallback((key: TranslationKey, params?: Record<string, string | number>): string => {
    let text: string = translations[locale]?.[key] || translations.fr[key] || key;
    if (params) {
      Object.entries(params).forEach(([k, v]) => {
        text = text.replace(`{${k}}`, String(v));
      });
    }
    return text;
  }, [locale]);

  return (
    <I18nContext.Provider value={{ locale, setLocale, t }}>
      {children}
    </I18nContext.Provider>
  );
}

export function useI18n() {
  const ctx = useContext(I18nContext);
  if (!ctx) throw new Error('useI18n must be used within I18nProvider');
  return ctx;
}
